version: "3"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:user/src/app:ro
    command:
      - uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
    - ./.env
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - USER_AGENT=${USER_AGENT}
      - ADMIN_SECRET=${ADMIN_SECRET}
  postgres:
    image: postgres
    environment:
      - POSTGRESS_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRESS_DB=${DATABASE_NAME
    volumes:
      - postgress_db:/var/lib/postgresql/data

volumes:
  postgress_db:
